<Project>
  <PropertyGroup>
    <Version>2.1.0-preview.2</Version>
    <LangVersion>latestMajor</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AnalysisLevel>latest</AnalysisLevel>
    <Authors>ISkyPro contributors</Authors>
    <Copyright>Copyright 2026 ISkyPro contributors</Copyright>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/Zephdyn/ISkyPro.Wiki</RepositoryUrl>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
