// <auto-generated />
#nullable enable
using System.Text.Json;

namespace ISkyPro.PluginSdk.V2;

public sealed record PluginV2SdkMethodDescriptor(
    string Name,
    string Permission,
    string Stability,
    string? RequestModel,
    string? ResponseModel,
    bool DefaultEnabled);

public static class PluginV2SdkMethods
{
    public const string SdkVersion = "2.1.0-preview.1";

    public const string ChannelsCreateSubChannel = "channels.createSubChannel";
    public const string ChannelsDeleteSubChannel = "channels.deleteSubChannel";
    public const string ChannelsGetChannel = "channels.getChannel";
    public const string ChannelsUpdateSubChannel = "channels.updateSubChannel";
    public const string GroupsGetGroupInfo = "groups.getGroupInfo";
    public const string GuildsGetGuild = "guilds.getGuild";
    public const string MediaUploadC2CFile = "media.uploadC2CFile";
    public const string MediaUploadChannelFile = "media.uploadChannelFile";
    public const string MediaUploadGroupFile = "media.uploadGroupFile";
    public const string MembersGetMember = "members.getMember";
    public const string MembersListMembers = "members.listMembers";
    public const string PermissionsGetApiPermissions = "permissions.getApiPermissions";
    public const string PermissionsRequestApiPermissionDemand = "permissions.requestApiPermissionDemand";
    public const string UnsafeRawOpenApi = "unsafe.rawOpenApi";
    public const string UsersGetCurrentBot = "users.getCurrentBot";
    public const string UsersGetUser = "users.getUser";

    public static IReadOnlyDictionary<string, PluginV2SdkMethodDescriptor> Catalog { get; } =
        new Dictionary<string, PluginV2SdkMethodDescriptor>(StringComparer.Ordinal)
        {
            [ChannelsCreateSubChannel] = new(ChannelsCreateSubChannel, "channels.manage", "stable", "CreateChannelRequest", "Channel", true),
            [ChannelsDeleteSubChannel] = new(ChannelsDeleteSubChannel, "channels.manage", "stable", null, "Empty", true),
            [ChannelsGetChannel] = new(ChannelsGetChannel, "guilds.read", "stable", null, "Channel", true),
            [ChannelsUpdateSubChannel] = new(ChannelsUpdateSubChannel, "channels.manage", "stable", "UpdateChannelRequest", "Channel", true),
            [GroupsGetGroupInfo] = new(GroupsGetGroupInfo, "groups.read", "preview", null, "Group", true),
            [GuildsGetGuild] = new(GuildsGetGuild, "guilds.read", "stable", null, "Guild", true),
            [MediaUploadC2CFile] = new(MediaUploadC2CFile, "media.upload", "stable", "C2CFileUploadRequest", "FileUploadResponse", true),
            [MediaUploadChannelFile] = new(MediaUploadChannelFile, "media.upload", "preview", "ChannelFileUploadRequest", "FileUploadResponse", true),
            [MediaUploadGroupFile] = new(MediaUploadGroupFile, "media.upload", "stable", "GroupFileUploadRequest", "FileUploadResponse", true),
            [MembersGetMember] = new(MembersGetMember, "members.read", "stable", null, "Member", true),
            [MembersListMembers] = new(MembersListMembers, "members.read", "stable", null, "MemberList", true),
            [PermissionsGetApiPermissions] = new(PermissionsGetApiPermissions, "permissions.manage", "stable", null, "ApiPermissionList", true),
            [PermissionsRequestApiPermissionDemand] = new(PermissionsRequestApiPermissionDemand, "permissions.manage", "stable", "ApiPermissionDemandRequest", "ApiPermissionDemand", true),
            [UnsafeRawOpenApi] = new(UnsafeRawOpenApi, "unsafe.raw-open-api", "unsafe", "RawOpenApiRequest", "RawOpenApiResponse", false),
            [UsersGetCurrentBot] = new(UsersGetCurrentBot, "users.read", "stable", null, "BotUser", true),
            [UsersGetUser] = new(UsersGetUser, "users.read", "preview", null, "User", true),
        };

    public static IReadOnlyDictionary<string, string> Permissions { get; } = Catalog
        .ToDictionary(item => item.Key, item => item.Value.Permission, StringComparer.Ordinal);
}

public static class GeneratedPluginV2ContextExtensions
{
    private static readonly IReadOnlyDictionary<string, object?> EmptyParameters =
        new Dictionary<string, object?>();

    public static ValueTask<JsonElement> ChannelsCreateSubChannelAsync(
        this IISkyProPluginV2Context context,
        IReadOnlyDictionary<string, object?>? parameters = null,
        CancellationToken cancellationToken = default)
    {
        return context.InvokeWithResultAsync(PluginV2SdkMethods.ChannelsCreateSubChannel, parameters ?? EmptyParameters, cancellationToken);
    }

    public static ValueTask<JsonElement> ChannelsDeleteSubChannelAsync(
        this IISkyProPluginV2Context context,
        IReadOnlyDictionary<string, object?>? parameters = null,
        CancellationToken cancellationToken = default)
    {
        return context.InvokeWithResultAsync(PluginV2SdkMethods.ChannelsDeleteSubChannel, parameters ?? EmptyParameters, cancellationToken);
    }

    public static ValueTask<JsonElement> ChannelsGetChannelAsync(
        this IISkyProPluginV2Context context,
        IReadOnlyDictionary<string, object?>? parameters = null,
        CancellationToken cancellationToken = default)
    {
        return context.InvokeWithResultAsync(PluginV2SdkMethods.ChannelsGetChannel, parameters ?? EmptyParameters, cancellationToken);
    }

    public static ValueTask<JsonElement> ChannelsUpdateSubChannelAsync(
        this IISkyProPluginV2Context context,
        IReadOnlyDictionary<string, object?>? parameters = null,
        CancellationToken cancellationToken = default)
    {
        return context.InvokeWithResultAsync(PluginV2SdkMethods.ChannelsUpdateSubChannel, parameters ?? EmptyParameters, cancellationToken);
    }

    public static ValueTask<JsonElement> GroupsGetGroupInfoAsync(
        this IISkyProPluginV2Context context,
        IReadOnlyDictionary<string, object?>? parameters = null,
        CancellationToken cancellationToken = default)
    {
        return context.InvokeWithResultAsync(PluginV2SdkMethods.GroupsGetGroupInfo, parameters ?? EmptyParameters, cancellationToken);
    }

    public static ValueTask<JsonElement> GuildsGetGuildAsync(
        this IISkyProPluginV2Context context,
        IReadOnlyDictionary<string, object?>? parameters = null,
        CancellationToken cancellationToken = default)
    {
        return context.InvokeWithResultAsync(PluginV2SdkMethods.GuildsGetGuild, parameters ?? EmptyParameters, cancellationToken);
    }

    public static ValueTask<JsonElement> MediaUploadC2CFileAsync(
        this IISkyProPluginV2Context context,
        IReadOnlyDictionary<string, object?>? parameters = null,
        CancellationToken cancellationToken = default)
    {
        return context.InvokeWithResultAsync(PluginV2SdkMethods.MediaUploadC2CFile, parameters ?? EmptyParameters, cancellationToken);
    }

    public static ValueTask<JsonElement> MediaUploadChannelFileAsync(
        this IISkyProPluginV2Context context,
        IReadOnlyDictionary<string, object?>? parameters = null,
        CancellationToken cancellationToken = default)
    {
        return context.InvokeWithResultAsync(PluginV2SdkMethods.MediaUploadChannelFile, parameters ?? EmptyParameters, cancellationToken);
    }

    public static ValueTask<JsonElement> MediaUploadGroupFileAsync(
        this IISkyProPluginV2Context context,
        IReadOnlyDictionary<string, object?>? parameters = null,
        CancellationToken cancellationToken = default)
    {
        return context.InvokeWithResultAsync(PluginV2SdkMethods.MediaUploadGroupFile, parameters ?? EmptyParameters, cancellationToken);
    }

    public static ValueTask<JsonElement> MembersGetMemberAsync(
        this IISkyProPluginV2Context context,
        IReadOnlyDictionary<string, object?>? parameters = null,
        CancellationToken cancellationToken = default)
    {
        return context.InvokeWithResultAsync(PluginV2SdkMethods.MembersGetMember, parameters ?? EmptyParameters, cancellationToken);
    }

    public static ValueTask<JsonElement> MembersListMembersAsync(
        this IISkyProPluginV2Context context,
        IReadOnlyDictionary<string, object?>? parameters = null,
        CancellationToken cancellationToken = default)
    {
        return context.InvokeWithResultAsync(PluginV2SdkMethods.MembersListMembers, parameters ?? EmptyParameters, cancellationToken);
    }

    public static ValueTask<JsonElement> PermissionsGetApiPermissionsAsync(
        this IISkyProPluginV2Context context,
        IReadOnlyDictionary<string, object?>? parameters = null,
        CancellationToken cancellationToken = default)
    {
        return context.InvokeWithResultAsync(PluginV2SdkMethods.PermissionsGetApiPermissions, parameters ?? EmptyParameters, cancellationToken);
    }

    public static ValueTask<JsonElement> PermissionsRequestApiPermissionDemandAsync(
        this IISkyProPluginV2Context context,
        IReadOnlyDictionary<string, object?>? parameters = null,
        CancellationToken cancellationToken = default)
    {
        return context.InvokeWithResultAsync(PluginV2SdkMethods.PermissionsRequestApiPermissionDemand, parameters ?? EmptyParameters, cancellationToken);
    }

    public static ValueTask<JsonElement> UnsafeRawOpenApiAsync(
        this IISkyProPluginV2Context context,
        IReadOnlyDictionary<string, object?>? parameters = null,
        CancellationToken cancellationToken = default)
    {
        return context.InvokeWithResultAsync(PluginV2SdkMethods.UnsafeRawOpenApi, parameters ?? EmptyParameters, cancellationToken);
    }

    public static ValueTask<JsonElement> UsersGetCurrentBotAsync(
        this IISkyProPluginV2Context context,
        IReadOnlyDictionary<string, object?>? parameters = null,
        CancellationToken cancellationToken = default)
    {
        return context.InvokeWithResultAsync(PluginV2SdkMethods.UsersGetCurrentBot, parameters ?? EmptyParameters, cancellationToken);
    }

    public static ValueTask<JsonElement> UsersGetUserAsync(
        this IISkyProPluginV2Context context,
        IReadOnlyDictionary<string, object?>? parameters = null,
        CancellationToken cancellationToken = default)
    {
        return context.InvokeWithResultAsync(PluginV2SdkMethods.UsersGetUser, parameters ?? EmptyParameters, cancellationToken);
    }

}
