#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
VERSION_PROPS = ROOT / "Directory.Build.props"
CATALOG = ROOT / "sdk" / "catalog" / "qqbot-api.catalog.json"
CS_OUT = ROOT / "sdk" / "csharp" / "ISkyPro.PluginSdk" / "V2" / "GeneratedSdkMethods.cs"
PY_OUT = ROOT / "sdk" / "python" / "iskypro_sdk_v2" / "generated_methods.py"
NODE_OUT = ROOT / "sdk" / "node" / "iskypro-sdk-v2" / "generated-methods.js"
NODE_TYPES_OUT = ROOT / "sdk" / "node" / "iskypro-sdk-v2" / "generated-methods.d.ts"
GO_OUT = ROOT / "sdk" / "go" / "iskypro" / "generated_methods.go"


def words(name: str) -> list[str]:
    parts: list[str] = []
    for token in re.split(r"[^A-Za-z0-9]+", name):
        if not token:
            continue
        parts.extend(re.findall(r"[A-Z]+(?:\d+[A-Z]+)*(?=[A-Z][a-z]|$)|[A-Z]?[a-z]+|\d+", token))
    return parts


def pascal(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in words(name))


def camel(name: str) -> str:
    value = pascal(name)
    return value[:1].lower() + value[1:]


def snake(name: str) -> str:
    return "_".join(part.lower() for part in words(name))


def load_version() -> str:
    root = ET.fromstring(VERSION_PROPS.read_text(encoding="utf-8"))
    version = root.findtext(".//Version", default="").strip()
    if not version:
        raise RuntimeError(f"Version is missing from {VERSION_PROPS}")
    return version


def load_endpoints() -> list[dict[str, object]]:
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    return sorted(catalog["endpoints"], key=lambda item: item["name"])


def csharp_literal(value: object) -> str:
    if value is None:
        return "null"
    return json.dumps(str(value))


def render_csharp(version: str, endpoints: list[dict[str, object]]) -> str:
    lines = [
        "// <auto-generated />",
        "#nullable enable",
        "using System.Text.Json;",
        "",
        "namespace ISkyPro.PluginSdk.V2;",
        "",
        "public sealed record PluginV2SdkMethodDescriptor(",
        "    string Name,",
        "    string Permission,",
        "    string Stability,",
        "    string? RequestModel,",
        "    string? ResponseModel,",
        "    bool DefaultEnabled);",
        "",
        "public static class PluginV2SdkMethods",
        "{",
        f'    public const string SdkVersion = "{version}";',
        "",
    ]
    for endpoint in endpoints:
        lines.append(f'    public const string {pascal(str(endpoint["name"]))} = "{endpoint["name"]}";')
    lines.extend([
        "",
        "    public static IReadOnlyDictionary<string, PluginV2SdkMethodDescriptor> Catalog { get; } =",
        "        new Dictionary<string, PluginV2SdkMethodDescriptor>(StringComparer.Ordinal)",
        "        {",
    ])
    for endpoint in endpoints:
        method_name = pascal(str(endpoint["name"]))
        lines.append(
            f"            [{method_name}] = new({method_name}, \"{endpoint['permission']}\", "
            f"\"{endpoint['stability']}\", {csharp_literal(endpoint.get('requestModel'))}, "
            f"{csharp_literal(endpoint.get('responseModel'))}, "
            f"{str(bool(endpoint.get('defaultEnabled'))).lower()}),"
        )
    lines.extend([
        "        };",
        "",
        "    public static IReadOnlyDictionary<string, string> Permissions { get; } = Catalog",
        "        .ToDictionary(item => item.Key, item => item.Value.Permission, StringComparer.Ordinal);",
        "}",
        "",
        "public static class GeneratedPluginV2ContextExtensions",
        "{",
        "    private static readonly IReadOnlyDictionary<string, object?> EmptyParameters =",
        "        new Dictionary<string, object?>();",
        "",
    ])
    for endpoint in endpoints:
        method_name = pascal(str(endpoint["name"]))
        lines.extend([
            f"    public static ValueTask<JsonElement> {method_name}Async(",
            "        this IISkyProPluginV2Context context,",
            "        IReadOnlyDictionary<string, object?>? parameters = null,",
            "        CancellationToken cancellationToken = default)",
            "    {",
            f"        return context.InvokeWithResultAsync(PluginV2SdkMethods.{method_name}, parameters ?? EmptyParameters, cancellationToken);",
            "    }",
            "",
        ])
    lines.extend(["}", ""])
    return "\n".join(lines)


def python_literal(value: object) -> str:
    if value is None:
        return "None"
    if isinstance(value, bool):
        return "True" if value else "False"
    return repr(str(value))


def render_python(version: str, endpoints: list[dict[str, object]]) -> str:
    lines = [
        "# <auto-generated />",
        "from typing import Any, Mapping, Optional",
        "",
        f'SDK_VERSION = "{version}"',
        "SDK_METHODS = {",
    ]
    for endpoint in endpoints:
        lines.append(
            f'    "{snake(str(endpoint["name"]))}": '
            "{"
            f'"name": "{endpoint["name"]}", '
            f'"permission": "{endpoint["permission"]}", '
            f'"stability": "{endpoint["stability"]}", '
            f'"request_model": {python_literal(endpoint.get("requestModel"))}, '
            f'"response_model": {python_literal(endpoint.get("responseModel"))}, '
            f'"default_enabled": {python_literal(bool(endpoint.get("defaultEnabled")))}'
            "},"
        )
    lines.extend([
        "}",
        "",
        "",
        "class GeneratedSdkMethodsMixin:",
    ])
    for endpoint in endpoints:
        function_name = snake(str(endpoint["name"]))
        lines.extend([
            f"    def {function_name}(",
            "        self, parameters: Optional[Mapping[str, Any]] = None",
            "    ) -> Any:",
            f'        return self.invoke("{endpoint["name"]}", dict(parameters or {{}}))',
            "",
        ])
    return "\n".join(lines)


def render_node(version: str, endpoints: list[dict[str, object]]) -> str:
    lines = [
        "// <auto-generated />",
        f'export const sdkVersion = "{version}";',
        "",
        "export const sdkMethods = Object.freeze({",
    ]
    for endpoint in endpoints:
        request_model = json.dumps(endpoint.get("requestModel"))
        response_model = json.dumps(endpoint.get("responseModel"))
        default_enabled = str(bool(endpoint.get("defaultEnabled"))).lower()
        lines.append(
            f'  {camel(str(endpoint["name"]))}: Object.freeze({{ '
            f'name: "{endpoint["name"]}", permission: "{endpoint["permission"]}", '
            f'stability: "{endpoint["stability"]}", requestModel: {request_model}, '
            f'responseModel: {response_model}, defaultEnabled: {default_enabled} }}),'
        )
    lines.extend([
        "});",
        "",
        "export class GeneratedSdkMethods {",
    ])
    for endpoint in endpoints:
        lines.extend([
            "  /**",
            "   * @param {Record<string, unknown>} [parameters]",
            "   * @returns {Promise<unknown>}",
            "   */",
            f"  {camel(str(endpoint['name']))}(parameters = {{}}) {{",
            f'    return this.invoke("{endpoint["name"]}", parameters);',
            "  }",
            "",
        ])
    lines.extend(["}", ""])
    return "\n".join(lines)


def render_node_types(endpoints: list[dict[str, object]]) -> str:
    lines = [
        "// <auto-generated />",
        "export type JsonObject = Record<string, unknown>;",
        "",
        "export interface SdkMethodDescriptor {",
        "  readonly name: string;",
        "  readonly permission: string;",
        "  readonly stability: string;",
        "  readonly requestModel: string | null;",
        "  readonly responseModel: string | null;",
        "  readonly defaultEnabled: boolean;",
        "}",
        "",
        "export const sdkVersion: string;",
        "export const sdkMethods: Readonly<Record<string, SdkMethodDescriptor>>;",
        "",
        "export class GeneratedSdkMethods {",
        "  invoke(method: string, parameters?: JsonObject): Promise<unknown>;",
    ]
    for endpoint in endpoints:
        lines.append(
            f"  {camel(str(endpoint['name']))}(parameters?: JsonObject): Promise<unknown>;"
        )
    lines.extend(["}", ""])
    return "\n".join(lines)


def render_go(version: str, endpoints: list[dict[str, object]]) -> str:
    method_keys = [json.dumps(pascal(str(endpoint["name"]))) for endpoint in endpoints]
    method_name_keys = [json.dumps(str(endpoint["name"])) for endpoint in endpoints]
    method_key_width = max(map(len, method_keys))
    method_name_key_width = max(map(len, method_name_keys))
    lines = [
        "// <auto-generated />",
        "package iskypro",
        "",
        'import "context"',
        "",
        f'const SDKVersion = "{version}"',
        "",
        "var SDKMethods = map[string]SdkMethod{",
    ]
    for endpoint, method_key in zip(endpoints, method_keys, strict=True):
        request_model = json.dumps(endpoint.get("requestModel") or "")
        response_model = json.dumps(endpoint.get("responseModel") or "")
        default_enabled = str(bool(endpoint.get("defaultEnabled"))).lower()
        lines.append(
            f'\t{method_key + ":":<{method_key_width + 2}}{{Name: {json.dumps(str(endpoint["name"]))}, '
            f'Permission: {json.dumps(str(endpoint["permission"]))}, '
            f'Stability: {json.dumps(str(endpoint["stability"]))}, RequestModel: {request_model}, '
            f'ResponseModel: {response_model}, DefaultEnabled: {default_enabled}}},'
        )
    lines.extend([
        "}",
        "",
        "var SDKMethodPermissions = map[string]string{",
    ])
    for endpoint, method_name_key in zip(endpoints, method_name_keys, strict=True):
        lines.append(
            f'\t{method_name_key + ":":<{method_name_key_width + 2}}{json.dumps(str(endpoint["permission"]))},'
        )
    lines.extend(["}", ""])
    for endpoint in endpoints:
        method_name = pascal(str(endpoint["name"]))
        lines.extend([
            f"func (c *PluginContext) {method_name}(ctx context.Context, parameters JsonObject) (any, error) {{",
            f'\treturn c.Invoke(ctx, "{endpoint["name"]}", parameters)',
            "}",
            "",
        ])
    return "\n".join(lines)


def replace_field(content: str, field: str, value: str) -> str:
    pattern = re.compile(rf'("{re.escape(field)}"\s*:\s*")[^"]+("\s*[,}}])')
    updated, count = pattern.subn(rf"\g<1>{value}\g<2>", content, count=1)
    if count != 1:
        raise RuntimeError(f"Unable to update JSON field {field!r}")
    return updated


def expected_version_files(version: str) -> dict[Path, str]:
    targets: dict[Path, str] = {}
    json_targets = [
        (ROOT / "package.json", "version"),
        (ROOT / "sdk" / "node" / "iskypro-sdk-v2" / "package.json", "version"),
        (CATALOG, "version"),
        (ROOT / "samples" / "ISkyPro.SamplePlugin" / "manifest.json", "sdkVersion"),
        (ROOT / "samples" / "stdio-python-plugin" / "manifest.json", "sdkVersion"),
        (ROOT / "samples" / "stdio-node-plugin" / "manifest.json", "sdkVersion"),
        (ROOT / "samples" / "stdio-go-plugin" / "manifest.json", "sdkVersion"),
    ]
    for path, field in json_targets:
        targets[path] = replace_field(path.read_text(encoding="utf-8"), field, version)

    pyproject = ROOT / "sdk" / "python" / "pyproject.toml"
    pyproject_text, count = re.subn(
        r'(?m)^version\s*=\s*"[^"]+"$',
        f'version = "{version}"',
        pyproject.read_text(encoding="utf-8"),
        count=1,
    )
    if count != 1:
        raise RuntimeError(f"Unable to update Python package version in {pyproject}")
    targets[pyproject] = pyproject_text

    go_sample_mod = ROOT / "samples" / "stdio-go-plugin" / "go.mod"
    go_module_path = "github.com/Zephdyn/ISkyPro.Wiki/sdk/go/iskypro/v2"
    go_mod_text, count = re.subn(
        rf"(?m)^(require\s+{re.escape(go_module_path)}\s+)v\S+$",
        rf"\g<1>v{version}",
        go_sample_mod.read_text(encoding="utf-8"),
        count=1,
    )
    if count != 1:
        raise RuntimeError(f"Unable to update Go sample SDK version in {go_sample_mod}")
    targets[go_sample_mod] = go_mod_text

    return targets


def write_or_check(expected: dict[Path, str], check: bool) -> list[Path]:
    stale: list[Path] = []
    for path, content in expected.items():
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        normalized = content.replace("\r\n", "\n")
        if current.replace("\r\n", "\n") == normalized:
            continue
        if check:
            stale.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(normalized, encoding="utf-8", newline="\n")
    return stale


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate and verify Plugin SDK v2 language surfaces.")
    parser.add_argument("--check", action="store_true", help="Fail if generated files or SDK versions are stale.")
    args = parser.parse_args()

    version = load_version()
    endpoints = load_endpoints()
    expected = {
        CS_OUT: render_csharp(version, endpoints),
        PY_OUT: render_python(version, endpoints),
        NODE_OUT: render_node(version, endpoints),
        NODE_TYPES_OUT: render_node_types(endpoints),
        GO_OUT: render_go(version, endpoints),
        **expected_version_files(version),
    }
    stale = write_or_check(expected, args.check)
    if stale:
        print("Plugin SDK generated files are stale:", file=sys.stderr)
        for path in stale:
            print(f"  {path.relative_to(ROOT)}", file=sys.stderr)
        print("Run: python tools/plugin-sdk-stub-generator/generate.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
