// <auto-generated />
package iskypro

import "context"

const SDKVersion = "2.0.0"

var SDKMethods = map[string]SdkMethod{
	"ChannelsCreateSubChannel":              {Name: "channels.createSubChannel", Permission: "channels.manage", Stability: "stable", RequestModel: "CreateChannelRequest", ResponseModel: "Channel", DefaultEnabled: true},
	"ChannelsDeleteSubChannel":              {Name: "channels.deleteSubChannel", Permission: "channels.manage", Stability: "stable", RequestModel: "", ResponseModel: "Empty", DefaultEnabled: true},
	"ChannelsGetChannel":                    {Name: "channels.getChannel", Permission: "guilds.read", Stability: "stable", RequestModel: "", ResponseModel: "Channel", DefaultEnabled: true},
	"ChannelsUpdateSubChannel":              {Name: "channels.updateSubChannel", Permission: "channels.manage", Stability: "stable", RequestModel: "UpdateChannelRequest", ResponseModel: "Channel", DefaultEnabled: true},
	"GroupsGetGroupInfo":                    {Name: "groups.getGroupInfo", Permission: "groups.read", Stability: "preview", RequestModel: "", ResponseModel: "Group", DefaultEnabled: true},
	"GuildsGetGuild":                        {Name: "guilds.getGuild", Permission: "guilds.read", Stability: "stable", RequestModel: "", ResponseModel: "Guild", DefaultEnabled: true},
	"MediaUploadC2CFile":                    {Name: "media.uploadC2CFile", Permission: "media.upload", Stability: "stable", RequestModel: "C2CFileUploadRequest", ResponseModel: "FileUploadResponse", DefaultEnabled: true},
	"MediaUploadChannelFile":                {Name: "media.uploadChannelFile", Permission: "media.upload", Stability: "preview", RequestModel: "ChannelFileUploadRequest", ResponseModel: "FileUploadResponse", DefaultEnabled: true},
	"MediaUploadGroupFile":                  {Name: "media.uploadGroupFile", Permission: "media.upload", Stability: "stable", RequestModel: "GroupFileUploadRequest", ResponseModel: "FileUploadResponse", DefaultEnabled: true},
	"MembersGetMember":                      {Name: "members.getMember", Permission: "members.read", Stability: "stable", RequestModel: "", ResponseModel: "Member", DefaultEnabled: true},
	"MembersListMembers":                    {Name: "members.listMembers", Permission: "members.read", Stability: "stable", RequestModel: "", ResponseModel: "MemberList", DefaultEnabled: true},
	"MessagesReplyMarkdown":                 {Name: "messages.replyMarkdown", Permission: "messages.reply", Stability: "preview", RequestModel: "GroupMarkdownMessageRequest", ResponseModel: "MessageResponse", DefaultEnabled: true},
	"MessagesReplyMedia":                    {Name: "messages.replyMedia", Permission: "messages.reply", Stability: "preview", RequestModel: "GroupMediaMessageRequest", ResponseModel: "MessageResponse", DefaultEnabled: true},
	"MessagesReplyText":                     {Name: "messages.replyText", Permission: "messages.reply", Stability: "stable", RequestModel: "GroupTextMessageRequest", ResponseModel: "MessageResponse", DefaultEnabled: true},
	"MessagesSendC2CText":                   {Name: "messages.sendC2CText", Permission: "messages.send", Stability: "stable", RequestModel: "C2CTextMessageRequest", ResponseModel: "MessageResponse", DefaultEnabled: true},
	"MessagesSendChannelText":               {Name: "messages.sendChannelText", Permission: "messages.send", Stability: "stable", RequestModel: "ChannelTextMessageRequest", ResponseModel: "MessageResponse", DefaultEnabled: true},
	"MessagesSendDirectMessage":             {Name: "messages.sendDirectMessage", Permission: "messages.send", Stability: "stable", RequestModel: "DirectTextMessageRequest", ResponseModel: "MessageResponse", DefaultEnabled: true},
	"MessagesSendGroupText":                 {Name: "messages.sendGroupText", Permission: "messages.send", Stability: "stable", RequestModel: "GroupTextMessageRequest", ResponseModel: "MessageResponse", DefaultEnabled: true},
	"PermissionsGetApiPermissions":          {Name: "permissions.getApiPermissions", Permission: "permissions.manage", Stability: "stable", RequestModel: "", ResponseModel: "ApiPermissionList", DefaultEnabled: true},
	"PermissionsRequestApiPermissionDemand": {Name: "permissions.requestApiPermissionDemand", Permission: "permissions.manage", Stability: "stable", RequestModel: "ApiPermissionDemandRequest", ResponseModel: "ApiPermissionDemand", DefaultEnabled: true},
	"UnsafeRawOpenApi":                      {Name: "unsafe.rawOpenApi", Permission: "unsafe.raw-open-api", Stability: "unsafe", RequestModel: "RawOpenApiRequest", ResponseModel: "RawOpenApiResponse", DefaultEnabled: false},
	"UsersGetCurrentBot":                    {Name: "users.getCurrentBot", Permission: "users.read", Stability: "stable", RequestModel: "", ResponseModel: "BotUser", DefaultEnabled: true},
	"UsersGetUser":                          {Name: "users.getUser", Permission: "users.read", Stability: "preview", RequestModel: "", ResponseModel: "User", DefaultEnabled: true},
}

var SDKMethodPermissions = map[string]string{
	"channels.createSubChannel":              "channels.manage",
	"channels.deleteSubChannel":              "channels.manage",
	"channels.getChannel":                    "guilds.read",
	"channels.updateSubChannel":              "channels.manage",
	"groups.getGroupInfo":                    "groups.read",
	"guilds.getGuild":                        "guilds.read",
	"media.uploadC2CFile":                    "media.upload",
	"media.uploadChannelFile":                "media.upload",
	"media.uploadGroupFile":                  "media.upload",
	"members.getMember":                      "members.read",
	"members.listMembers":                    "members.read",
	"messages.replyMarkdown":                 "messages.reply",
	"messages.replyMedia":                    "messages.reply",
	"messages.replyText":                     "messages.reply",
	"messages.sendC2CText":                   "messages.send",
	"messages.sendChannelText":               "messages.send",
	"messages.sendDirectMessage":             "messages.send",
	"messages.sendGroupText":                 "messages.send",
	"permissions.getApiPermissions":          "permissions.manage",
	"permissions.requestApiPermissionDemand": "permissions.manage",
	"unsafe.rawOpenApi":                      "unsafe.raw-open-api",
	"users.getCurrentBot":                    "users.read",
	"users.getUser":                          "users.read",
}

func (c *PluginContext) ChannelsCreateSubChannel(ctx context.Context, parameters JsonObject) (any, error) {
	return c.Invoke(ctx, "channels.createSubChannel", parameters)
}

func (c *PluginContext) ChannelsDeleteSubChannel(ctx context.Context, parameters JsonObject) (any, error) {
	return c.Invoke(ctx, "channels.deleteSubChannel", parameters)
}

func (c *PluginContext) ChannelsGetChannel(ctx context.Context, parameters JsonObject) (any, error) {
	return c.Invoke(ctx, "channels.getChannel", parameters)
}

func (c *PluginContext) ChannelsUpdateSubChannel(ctx context.Context, parameters JsonObject) (any, error) {
	return c.Invoke(ctx, "channels.updateSubChannel", parameters)
}

func (c *PluginContext) GroupsGetGroupInfo(ctx context.Context, parameters JsonObject) (any, error) {
	return c.Invoke(ctx, "groups.getGroupInfo", parameters)
}

func (c *PluginContext) GuildsGetGuild(ctx context.Context, parameters JsonObject) (any, error) {
	return c.Invoke(ctx, "guilds.getGuild", parameters)
}

func (c *PluginContext) MediaUploadC2CFile(ctx context.Context, parameters JsonObject) (any, error) {
	return c.Invoke(ctx, "media.uploadC2CFile", parameters)
}

func (c *PluginContext) MediaUploadChannelFile(ctx context.Context, parameters JsonObject) (any, error) {
	return c.Invoke(ctx, "media.uploadChannelFile", parameters)
}

func (c *PluginContext) MediaUploadGroupFile(ctx context.Context, parameters JsonObject) (any, error) {
	return c.Invoke(ctx, "media.uploadGroupFile", parameters)
}

func (c *PluginContext) MembersGetMember(ctx context.Context, parameters JsonObject) (any, error) {
	return c.Invoke(ctx, "members.getMember", parameters)
}

func (c *PluginContext) MembersListMembers(ctx context.Context, parameters JsonObject) (any, error) {
	return c.Invoke(ctx, "members.listMembers", parameters)
}

func (c *PluginContext) MessagesReplyMarkdown(ctx context.Context, parameters JsonObject) (any, error) {
	return c.Invoke(ctx, "messages.replyMarkdown", parameters)
}

func (c *PluginContext) MessagesReplyMedia(ctx context.Context, parameters JsonObject) (any, error) {
	return c.Invoke(ctx, "messages.replyMedia", parameters)
}

func (c *PluginContext) MessagesReplyText(ctx context.Context, parameters JsonObject) (any, error) {
	return c.Invoke(ctx, "messages.replyText", parameters)
}

func (c *PluginContext) MessagesSendC2CText(ctx context.Context, parameters JsonObject) (any, error) {
	return c.Invoke(ctx, "messages.sendC2CText", parameters)
}

func (c *PluginContext) MessagesSendChannelText(ctx context.Context, parameters JsonObject) (any, error) {
	return c.Invoke(ctx, "messages.sendChannelText", parameters)
}

func (c *PluginContext) MessagesSendDirectMessage(ctx context.Context, parameters JsonObject) (any, error) {
	return c.Invoke(ctx, "messages.sendDirectMessage", parameters)
}

func (c *PluginContext) MessagesSendGroupText(ctx context.Context, parameters JsonObject) (any, error) {
	return c.Invoke(ctx, "messages.sendGroupText", parameters)
}

func (c *PluginContext) PermissionsGetApiPermissions(ctx context.Context, parameters JsonObject) (any, error) {
	return c.Invoke(ctx, "permissions.getApiPermissions", parameters)
}

func (c *PluginContext) PermissionsRequestApiPermissionDemand(ctx context.Context, parameters JsonObject) (any, error) {
	return c.Invoke(ctx, "permissions.requestApiPermissionDemand", parameters)
}

func (c *PluginContext) UnsafeRawOpenApi(ctx context.Context, parameters JsonObject) (any, error) {
	return c.Invoke(ctx, "unsafe.rawOpenApi", parameters)
}

func (c *PluginContext) UsersGetCurrentBot(ctx context.Context, parameters JsonObject) (any, error) {
	return c.Invoke(ctx, "users.getCurrentBot", parameters)
}

func (c *PluginContext) UsersGetUser(ctx context.Context, parameters JsonObject) (any, error) {
	return c.Invoke(ctx, "users.getUser", parameters)
}
