# <auto-generated />
from typing import Any, Mapping, Optional

SDK_VERSION = "2.0.0"
SDK_METHODS = {
    "channels_create_sub_channel": {"name": "channels.createSubChannel", "permission": "channels.manage", "stability": "stable", "request_model": 'CreateChannelRequest', "response_model": 'Channel', "default_enabled": True},
    "channels_delete_sub_channel": {"name": "channels.deleteSubChannel", "permission": "channels.manage", "stability": "stable", "request_model": None, "response_model": 'Empty', "default_enabled": True},
    "channels_get_channel": {"name": "channels.getChannel", "permission": "guilds.read", "stability": "stable", "request_model": None, "response_model": 'Channel', "default_enabled": True},
    "channels_update_sub_channel": {"name": "channels.updateSubChannel", "permission": "channels.manage", "stability": "stable", "request_model": 'UpdateChannelRequest', "response_model": 'Channel', "default_enabled": True},
    "groups_get_group_info": {"name": "groups.getGroupInfo", "permission": "groups.read", "stability": "preview", "request_model": None, "response_model": 'Group', "default_enabled": True},
    "guilds_get_guild": {"name": "guilds.getGuild", "permission": "guilds.read", "stability": "stable", "request_model": None, "response_model": 'Guild', "default_enabled": True},
    "media_upload_c2c_file": {"name": "media.uploadC2CFile", "permission": "media.upload", "stability": "stable", "request_model": 'C2CFileUploadRequest', "response_model": 'FileUploadResponse', "default_enabled": True},
    "media_upload_channel_file": {"name": "media.uploadChannelFile", "permission": "media.upload", "stability": "preview", "request_model": 'ChannelFileUploadRequest', "response_model": 'FileUploadResponse', "default_enabled": True},
    "media_upload_group_file": {"name": "media.uploadGroupFile", "permission": "media.upload", "stability": "stable", "request_model": 'GroupFileUploadRequest', "response_model": 'FileUploadResponse', "default_enabled": True},
    "members_get_member": {"name": "members.getMember", "permission": "members.read", "stability": "stable", "request_model": None, "response_model": 'Member', "default_enabled": True},
    "members_list_members": {"name": "members.listMembers", "permission": "members.read", "stability": "stable", "request_model": None, "response_model": 'MemberList', "default_enabled": True},
    "messages_reply_markdown": {"name": "messages.replyMarkdown", "permission": "messages.reply", "stability": "preview", "request_model": 'GroupMarkdownMessageRequest', "response_model": 'MessageResponse', "default_enabled": True},
    "messages_reply_media": {"name": "messages.replyMedia", "permission": "messages.reply", "stability": "preview", "request_model": 'GroupMediaMessageRequest', "response_model": 'MessageResponse', "default_enabled": True},
    "messages_reply_text": {"name": "messages.replyText", "permission": "messages.reply", "stability": "stable", "request_model": 'GroupTextMessageRequest', "response_model": 'MessageResponse', "default_enabled": True},
    "messages_send_c2c_text": {"name": "messages.sendC2CText", "permission": "messages.send", "stability": "stable", "request_model": 'C2CTextMessageRequest', "response_model": 'MessageResponse', "default_enabled": True},
    "messages_send_channel_text": {"name": "messages.sendChannelText", "permission": "messages.send", "stability": "stable", "request_model": 'ChannelTextMessageRequest', "response_model": 'MessageResponse', "default_enabled": True},
    "messages_send_direct_message": {"name": "messages.sendDirectMessage", "permission": "messages.send", "stability": "stable", "request_model": 'DirectTextMessageRequest', "response_model": 'MessageResponse', "default_enabled": True},
    "messages_send_group_text": {"name": "messages.sendGroupText", "permission": "messages.send", "stability": "stable", "request_model": 'GroupTextMessageRequest', "response_model": 'MessageResponse', "default_enabled": True},
    "permissions_get_api_permissions": {"name": "permissions.getApiPermissions", "permission": "permissions.manage", "stability": "stable", "request_model": None, "response_model": 'ApiPermissionList', "default_enabled": True},
    "permissions_request_api_permission_demand": {"name": "permissions.requestApiPermissionDemand", "permission": "permissions.manage", "stability": "stable", "request_model": 'ApiPermissionDemandRequest', "response_model": 'ApiPermissionDemand', "default_enabled": True},
    "unsafe_raw_open_api": {"name": "unsafe.rawOpenApi", "permission": "unsafe.raw-open-api", "stability": "unsafe", "request_model": 'RawOpenApiRequest', "response_model": 'RawOpenApiResponse', "default_enabled": False},
    "users_get_current_bot": {"name": "users.getCurrentBot", "permission": "users.read", "stability": "stable", "request_model": None, "response_model": 'BotUser', "default_enabled": True},
    "users_get_user": {"name": "users.getUser", "permission": "users.read", "stability": "preview", "request_model": None, "response_model": 'User', "default_enabled": True},
}


class GeneratedSdkMethodsMixin:
    def channels_create_sub_channel(
        self, parameters: Optional[Mapping[str, Any]] = None
    ) -> Any:
        return self.invoke("channels.createSubChannel", dict(parameters or {}))

    def channels_delete_sub_channel(
        self, parameters: Optional[Mapping[str, Any]] = None
    ) -> Any:
        return self.invoke("channels.deleteSubChannel", dict(parameters or {}))

    def channels_get_channel(
        self, parameters: Optional[Mapping[str, Any]] = None
    ) -> Any:
        return self.invoke("channels.getChannel", dict(parameters or {}))

    def channels_update_sub_channel(
        self, parameters: Optional[Mapping[str, Any]] = None
    ) -> Any:
        return self.invoke("channels.updateSubChannel", dict(parameters or {}))

    def groups_get_group_info(
        self, parameters: Optional[Mapping[str, Any]] = None
    ) -> Any:
        return self.invoke("groups.getGroupInfo", dict(parameters or {}))

    def guilds_get_guild(
        self, parameters: Optional[Mapping[str, Any]] = None
    ) -> Any:
        return self.invoke("guilds.getGuild", dict(parameters or {}))

    def media_upload_c2c_file(
        self, parameters: Optional[Mapping[str, Any]] = None
    ) -> Any:
        return self.invoke("media.uploadC2CFile", dict(parameters or {}))

    def media_upload_channel_file(
        self, parameters: Optional[Mapping[str, Any]] = None
    ) -> Any:
        return self.invoke("media.uploadChannelFile", dict(parameters or {}))

    def media_upload_group_file(
        self, parameters: Optional[Mapping[str, Any]] = None
    ) -> Any:
        return self.invoke("media.uploadGroupFile", dict(parameters or {}))

    def members_get_member(
        self, parameters: Optional[Mapping[str, Any]] = None
    ) -> Any:
        return self.invoke("members.getMember", dict(parameters or {}))

    def members_list_members(
        self, parameters: Optional[Mapping[str, Any]] = None
    ) -> Any:
        return self.invoke("members.listMembers", dict(parameters or {}))

    def messages_reply_markdown(
        self, parameters: Optional[Mapping[str, Any]] = None
    ) -> Any:
        return self.invoke("messages.replyMarkdown", dict(parameters or {}))

    def messages_reply_media(
        self, parameters: Optional[Mapping[str, Any]] = None
    ) -> Any:
        return self.invoke("messages.replyMedia", dict(parameters or {}))

    def messages_reply_text(
        self, parameters: Optional[Mapping[str, Any]] = None
    ) -> Any:
        return self.invoke("messages.replyText", dict(parameters or {}))

    def messages_send_c2c_text(
        self, parameters: Optional[Mapping[str, Any]] = None
    ) -> Any:
        return self.invoke("messages.sendC2CText", dict(parameters or {}))

    def messages_send_channel_text(
        self, parameters: Optional[Mapping[str, Any]] = None
    ) -> Any:
        return self.invoke("messages.sendChannelText", dict(parameters or {}))

    def messages_send_direct_message(
        self, parameters: Optional[Mapping[str, Any]] = None
    ) -> Any:
        return self.invoke("messages.sendDirectMessage", dict(parameters or {}))

    def messages_send_group_text(
        self, parameters: Optional[Mapping[str, Any]] = None
    ) -> Any:
        return self.invoke("messages.sendGroupText", dict(parameters or {}))

    def permissions_get_api_permissions(
        self, parameters: Optional[Mapping[str, Any]] = None
    ) -> Any:
        return self.invoke("permissions.getApiPermissions", dict(parameters or {}))

    def permissions_request_api_permission_demand(
        self, parameters: Optional[Mapping[str, Any]] = None
    ) -> Any:
        return self.invoke("permissions.requestApiPermissionDemand", dict(parameters or {}))

    def unsafe_raw_open_api(
        self, parameters: Optional[Mapping[str, Any]] = None
    ) -> Any:
        return self.invoke("unsafe.rawOpenApi", dict(parameters or {}))

    def users_get_current_bot(
        self, parameters: Optional[Mapping[str, Any]] = None
    ) -> Any:
        return self.invoke("users.getCurrentBot", dict(parameters or {}))

    def users_get_user(
        self, parameters: Optional[Mapping[str, Any]] = None
    ) -> Any:
        return self.invoke("users.getUser", dict(parameters or {}))
