// <auto-generated />
export type JsonObject = Record<string, unknown>;

export interface SdkMethodDescriptor {
  readonly name: string;
  readonly permission: string;
  readonly stability: string;
  readonly requestModel: string | null;
  readonly responseModel: string | null;
  readonly defaultEnabled: boolean;
}

export const sdkVersion: string;
export const sdkMethods: Readonly<Record<string, SdkMethodDescriptor>>;

export class GeneratedSdkMethods {
  invoke(method: string, parameters?: JsonObject): Promise<unknown>;
  channelsCreateSubChannel(parameters?: JsonObject): Promise<unknown>;
  channelsDeleteSubChannel(parameters?: JsonObject): Promise<unknown>;
  channelsGetChannel(parameters?: JsonObject): Promise<unknown>;
  channelsUpdateSubChannel(parameters?: JsonObject): Promise<unknown>;
  groupsGetGroupInfo(parameters?: JsonObject): Promise<unknown>;
  guildsGetGuild(parameters?: JsonObject): Promise<unknown>;
  mediaUploadC2CFile(parameters?: JsonObject): Promise<unknown>;
  mediaUploadChannelFile(parameters?: JsonObject): Promise<unknown>;
  mediaUploadGroupFile(parameters?: JsonObject): Promise<unknown>;
  membersGetMember(parameters?: JsonObject): Promise<unknown>;
  membersListMembers(parameters?: JsonObject): Promise<unknown>;
  messagesReplyMarkdown(parameters?: JsonObject): Promise<unknown>;
  messagesReplyMedia(parameters?: JsonObject): Promise<unknown>;
  messagesReplyText(parameters?: JsonObject): Promise<unknown>;
  messagesSendC2CText(parameters?: JsonObject): Promise<unknown>;
  messagesSendChannelText(parameters?: JsonObject): Promise<unknown>;
  messagesSendDirectMessage(parameters?: JsonObject): Promise<unknown>;
  messagesSendGroupText(parameters?: JsonObject): Promise<unknown>;
  permissionsGetApiPermissions(parameters?: JsonObject): Promise<unknown>;
  permissionsRequestApiPermissionDemand(parameters?: JsonObject): Promise<unknown>;
  unsafeRawOpenApi(parameters?: JsonObject): Promise<unknown>;
  usersGetCurrentBot(parameters?: JsonObject): Promise<unknown>;
  usersGetUser(parameters?: JsonObject): Promise<unknown>;
}
