// <auto-generated />
export const sdkVersion = "2.0.0";

export const sdkMethods = Object.freeze({
  channelsCreateSubChannel: Object.freeze({ name: "channels.createSubChannel", permission: "channels.manage", stability: "stable", requestModel: "CreateChannelRequest", responseModel: "Channel", defaultEnabled: true }),
  channelsDeleteSubChannel: Object.freeze({ name: "channels.deleteSubChannel", permission: "channels.manage", stability: "stable", requestModel: null, responseModel: "Empty", defaultEnabled: true }),
  channelsGetChannel: Object.freeze({ name: "channels.getChannel", permission: "guilds.read", stability: "stable", requestModel: null, responseModel: "Channel", defaultEnabled: true }),
  channelsUpdateSubChannel: Object.freeze({ name: "channels.updateSubChannel", permission: "channels.manage", stability: "stable", requestModel: "UpdateChannelRequest", responseModel: "Channel", defaultEnabled: true }),
  groupsGetGroupInfo: Object.freeze({ name: "groups.getGroupInfo", permission: "groups.read", stability: "preview", requestModel: null, responseModel: "Group", defaultEnabled: true }),
  guildsGetGuild: Object.freeze({ name: "guilds.getGuild", permission: "guilds.read", stability: "stable", requestModel: null, responseModel: "Guild", defaultEnabled: true }),
  mediaUploadC2CFile: Object.freeze({ name: "media.uploadC2CFile", permission: "media.upload", stability: "stable", requestModel: "C2CFileUploadRequest", responseModel: "FileUploadResponse", defaultEnabled: true }),
  mediaUploadChannelFile: Object.freeze({ name: "media.uploadChannelFile", permission: "media.upload", stability: "preview", requestModel: "ChannelFileUploadRequest", responseModel: "FileUploadResponse", defaultEnabled: true }),
  mediaUploadGroupFile: Object.freeze({ name: "media.uploadGroupFile", permission: "media.upload", stability: "stable", requestModel: "GroupFileUploadRequest", responseModel: "FileUploadResponse", defaultEnabled: true }),
  membersGetMember: Object.freeze({ name: "members.getMember", permission: "members.read", stability: "stable", requestModel: null, responseModel: "Member", defaultEnabled: true }),
  membersListMembers: Object.freeze({ name: "members.listMembers", permission: "members.read", stability: "stable", requestModel: null, responseModel: "MemberList", defaultEnabled: true }),
  messagesReplyMarkdown: Object.freeze({ name: "messages.replyMarkdown", permission: "messages.reply", stability: "preview", requestModel: "GroupMarkdownMessageRequest", responseModel: "MessageResponse", defaultEnabled: true }),
  messagesReplyMedia: Object.freeze({ name: "messages.replyMedia", permission: "messages.reply", stability: "preview", requestModel: "GroupMediaMessageRequest", responseModel: "MessageResponse", defaultEnabled: true }),
  messagesReplyText: Object.freeze({ name: "messages.replyText", permission: "messages.reply", stability: "stable", requestModel: "GroupTextMessageRequest", responseModel: "MessageResponse", defaultEnabled: true }),
  messagesSendC2CText: Object.freeze({ name: "messages.sendC2CText", permission: "messages.send", stability: "stable", requestModel: "C2CTextMessageRequest", responseModel: "MessageResponse", defaultEnabled: true }),
  messagesSendChannelText: Object.freeze({ name: "messages.sendChannelText", permission: "messages.send", stability: "stable", requestModel: "ChannelTextMessageRequest", responseModel: "MessageResponse", defaultEnabled: true }),
  messagesSendDirectMessage: Object.freeze({ name: "messages.sendDirectMessage", permission: "messages.send", stability: "stable", requestModel: "DirectTextMessageRequest", responseModel: "MessageResponse", defaultEnabled: true }),
  messagesSendGroupText: Object.freeze({ name: "messages.sendGroupText", permission: "messages.send", stability: "stable", requestModel: "GroupTextMessageRequest", responseModel: "MessageResponse", defaultEnabled: true }),
  permissionsGetApiPermissions: Object.freeze({ name: "permissions.getApiPermissions", permission: "permissions.manage", stability: "stable", requestModel: null, responseModel: "ApiPermissionList", defaultEnabled: true }),
  permissionsRequestApiPermissionDemand: Object.freeze({ name: "permissions.requestApiPermissionDemand", permission: "permissions.manage", stability: "stable", requestModel: "ApiPermissionDemandRequest", responseModel: "ApiPermissionDemand", defaultEnabled: true }),
  unsafeRawOpenApi: Object.freeze({ name: "unsafe.rawOpenApi", permission: "unsafe.raw-open-api", stability: "unsafe", requestModel: "RawOpenApiRequest", responseModel: "RawOpenApiResponse", defaultEnabled: false }),
  usersGetCurrentBot: Object.freeze({ name: "users.getCurrentBot", permission: "users.read", stability: "stable", requestModel: null, responseModel: "BotUser", defaultEnabled: true }),
  usersGetUser: Object.freeze({ name: "users.getUser", permission: "users.read", stability: "preview", requestModel: null, responseModel: "User", defaultEnabled: true }),
});

export class GeneratedSdkMethods {
  /**
   * @param {Record<string, unknown>} [parameters]
   * @returns {Promise<unknown>}
   */
  channelsCreateSubChannel(parameters = {}) {
    return this.invoke("channels.createSubChannel", parameters);
  }

  /**
   * @param {Record<string, unknown>} [parameters]
   * @returns {Promise<unknown>}
   */
  channelsDeleteSubChannel(parameters = {}) {
    return this.invoke("channels.deleteSubChannel", parameters);
  }

  /**
   * @param {Record<string, unknown>} [parameters]
   * @returns {Promise<unknown>}
   */
  channelsGetChannel(parameters = {}) {
    return this.invoke("channels.getChannel", parameters);
  }

  /**
   * @param {Record<string, unknown>} [parameters]
   * @returns {Promise<unknown>}
   */
  channelsUpdateSubChannel(parameters = {}) {
    return this.invoke("channels.updateSubChannel", parameters);
  }

  /**
   * @param {Record<string, unknown>} [parameters]
   * @returns {Promise<unknown>}
   */
  groupsGetGroupInfo(parameters = {}) {
    return this.invoke("groups.getGroupInfo", parameters);
  }

  /**
   * @param {Record<string, unknown>} [parameters]
   * @returns {Promise<unknown>}
   */
  guildsGetGuild(parameters = {}) {
    return this.invoke("guilds.getGuild", parameters);
  }

  /**
   * @param {Record<string, unknown>} [parameters]
   * @returns {Promise<unknown>}
   */
  mediaUploadC2CFile(parameters = {}) {
    return this.invoke("media.uploadC2CFile", parameters);
  }

  /**
   * @param {Record<string, unknown>} [parameters]
   * @returns {Promise<unknown>}
   */
  mediaUploadChannelFile(parameters = {}) {
    return this.invoke("media.uploadChannelFile", parameters);
  }

  /**
   * @param {Record<string, unknown>} [parameters]
   * @returns {Promise<unknown>}
   */
  mediaUploadGroupFile(parameters = {}) {
    return this.invoke("media.uploadGroupFile", parameters);
  }

  /**
   * @param {Record<string, unknown>} [parameters]
   * @returns {Promise<unknown>}
   */
  membersGetMember(parameters = {}) {
    return this.invoke("members.getMember", parameters);
  }

  /**
   * @param {Record<string, unknown>} [parameters]
   * @returns {Promise<unknown>}
   */
  membersListMembers(parameters = {}) {
    return this.invoke("members.listMembers", parameters);
  }

  /**
   * @param {Record<string, unknown>} [parameters]
   * @returns {Promise<unknown>}
   */
  messagesReplyMarkdown(parameters = {}) {
    return this.invoke("messages.replyMarkdown", parameters);
  }

  /**
   * @param {Record<string, unknown>} [parameters]
   * @returns {Promise<unknown>}
   */
  messagesReplyMedia(parameters = {}) {
    return this.invoke("messages.replyMedia", parameters);
  }

  /**
   * @param {Record<string, unknown>} [parameters]
   * @returns {Promise<unknown>}
   */
  messagesReplyText(parameters = {}) {
    return this.invoke("messages.replyText", parameters);
  }

  /**
   * @param {Record<string, unknown>} [parameters]
   * @returns {Promise<unknown>}
   */
  messagesSendC2CText(parameters = {}) {
    return this.invoke("messages.sendC2CText", parameters);
  }

  /**
   * @param {Record<string, unknown>} [parameters]
   * @returns {Promise<unknown>}
   */
  messagesSendChannelText(parameters = {}) {
    return this.invoke("messages.sendChannelText", parameters);
  }

  /**
   * @param {Record<string, unknown>} [parameters]
   * @returns {Promise<unknown>}
   */
  messagesSendDirectMessage(parameters = {}) {
    return this.invoke("messages.sendDirectMessage", parameters);
  }

  /**
   * @param {Record<string, unknown>} [parameters]
   * @returns {Promise<unknown>}
   */
  messagesSendGroupText(parameters = {}) {
    return this.invoke("messages.sendGroupText", parameters);
  }

  /**
   * @param {Record<string, unknown>} [parameters]
   * @returns {Promise<unknown>}
   */
  permissionsGetApiPermissions(parameters = {}) {
    return this.invoke("permissions.getApiPermissions", parameters);
  }

  /**
   * @param {Record<string, unknown>} [parameters]
   * @returns {Promise<unknown>}
   */
  permissionsRequestApiPermissionDemand(parameters = {}) {
    return this.invoke("permissions.requestApiPermissionDemand", parameters);
  }

  /**
   * @param {Record<string, unknown>} [parameters]
   * @returns {Promise<unknown>}
   */
  unsafeRawOpenApi(parameters = {}) {
    return this.invoke("unsafe.rawOpenApi", parameters);
  }

  /**
   * @param {Record<string, unknown>} [parameters]
   * @returns {Promise<unknown>}
   */
  usersGetCurrentBot(parameters = {}) {
    return this.invoke("users.getCurrentBot", parameters);
  }

  /**
   * @param {Record<string, unknown>} [parameters]
   * @returns {Promise<unknown>}
   */
  usersGetUser(parameters = {}) {
    return this.invoke("users.getUser", parameters);
  }

}
