// <auto-generated />
export type JsonObject = Record<string, unknown>;

export interface SdkMethodDescriptor {
  readonly name: string;
  readonly permission: string;
  readonly stability: string;
  readonly requestModel: string | null;
  readonly responseModel: string | null;
  readonly defaultEnabled: boolean;
}

export const sdkVersion: string;
export const sdkMethods: Readonly<Record<string, SdkMethodDescriptor>>;

export class GeneratedSdkMethods {
  invoke(method: string, parameters?: JsonObject): Promise<unknown>;
  channelsCreateSubChannel(parameters?: JsonObject): Promise<unknown>;
  channelsDeleteSubChannel(parameters?: JsonObject): Promise<unknown>;
  channelsGetChannel(parameters?: JsonObject): Promise<unknown>;
  channelsUpdateSubChannel(parameters?: JsonObject): Promise<unknown>;
  groupsApproveJoinRequest(parameters?: JsonObject): Promise<unknown>;
  groupsCreateJoinApprovalStrategy(parameters?: JsonObject): Promise<unknown>;
  groupsDeleteJoinApprovalStrategy(parameters?: JsonObject): Promise<unknown>;
  groupsExecuteJoinApprovalStrategy(parameters?: JsonObject): Promise<unknown>;
  groupsGetBotState(parameters?: JsonObject): Promise<unknown>;
  groupsGetGroupInfo(parameters?: JsonObject): Promise<unknown>;
  groupsGetRestrictChatSetting(parameters?: JsonObject): Promise<unknown>;
  groupsListJoinApprovalStrategies(parameters?: JsonObject): Promise<unknown>;
  groupsListJoinRequests(parameters?: JsonObject): Promise<unknown>;
  groupsSetRestrictChatSetting(parameters?: JsonObject): Promise<unknown>;
  groupsUpdateJoinApprovalStrategy(parameters?: JsonObject): Promise<unknown>;
  groupsUpdateJoinApprovalStrategyWhitelist(parameters?: JsonObject): Promise<unknown>;
  guildsGetGuild(parameters?: JsonObject): Promise<unknown>;
  mediaUploadC2CFile(parameters?: JsonObject): Promise<unknown>;
  mediaUploadChannelFile(parameters?: JsonObject): Promise<unknown>;
  mediaUploadGroupFile(parameters?: JsonObject): Promise<unknown>;
  membersGetMember(parameters?: JsonObject): Promise<unknown>;
  membersListMembers(parameters?: JsonObject): Promise<unknown>;
  permissionsGetApiPermissions(parameters?: JsonObject): Promise<unknown>;
  permissionsRequestApiPermissionDemand(parameters?: JsonObject): Promise<unknown>;
  unsafeRawOpenApi(parameters?: JsonObject): Promise<unknown>;
  usersGetCurrentBot(parameters?: JsonObject): Promise<unknown>;
}
